### ISSUE TITLE
Can you put it on marketpalce for 2022 ?

### ISSUE THREAD

**Issue by rnied137** [0xotHik/Monokai-Theme-for-Visual-Studio-2019#1]
I know there are several monokai's themes but yours is way better. Can you put it in visual studio 2022 marketplace for easier install ?

**Comment by 0xotHik** [comment]
Have you tried https://marketplace.visualstudio.com/items?itemName=filipmazev.Sublime-Theme ? Used it for a bit, and it seems to do just the thing

**Comment by rnied137** [comment]
Yes it does job, sorry for spamming. I am closing thread. You really helped me m8.
